project:
  type: website
  title: "Eponymous Dictionary of Infectious Diseases"
  output-dir: _site

website:
  navbar:
    left:
      - text: "Preface"
        href: index.qmd
      - text: "Name index"
        href: entries.qmd

format:
  html:
    theme: default
    toc: true
    css: styles.css

editor: visual
